export type MessageRole = 'user' | 'assistant' | 'tool';

export type EffortLevel = 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max';

export interface ResponseMeta {
  model: string;
  effort?: EffortLevel;
}

export interface ToolCall {
  id: string;
  name: string;
  arguments: string;
}

export interface UserMessage {
  id: string;
  role: 'user';
  content: string;
  /** Which agent the user addressed, if any. Undefined = the default chat. */
  participantId?: string;
}

export interface AssistantMessage {
  id: string;
  role: 'assistant';
  content: string;
  isStreaming?: boolean;
  toolCalls?: ToolCall[];
  /** Authoring participant. Undefined = squirl's local LLM; otherwise a remote agent id. */
  participantId?: string;
  /** Model settings snapshotted when this response began. */
  responseMeta?: ResponseMeta;
  /** Identifies a system-initiated conversational prompt that was not generated by a model turn. */
  proactiveKind?: 'task-clarification' | 'delegation-confirmation';
  /** Structured state for a pending semantic delegation confirmation. */
  delegationConfirmation?: import('./agents/delegation.js').PendingDelegationConfirmation;
  /** Stable timestamp for cooldowns across runtime restarts. */
  createdAt?: string;
}

export interface ToolMessage {
  id: string;
  role: 'tool';
  toolCallId: string;
  toolName: string;
  content: string;
  /** Structured input captured when the tool started. Optional for legacy history. */
  toolInput?: unknown;
  /** Completion state. Undefined means a legacy completed tool result. */
  toolStatus?: 'running' | 'success' | 'error';
  /** True when the persisted output was shortened to the activity output limit. */
  outputTruncated?: boolean;
  /** Query text embedded for an automatic semantic-memory lookup. */
  memoryLookup?: { queries: string[] };
  /** Owning participant for tool activity surfaced from a remote agent. */
  participantId?: string;
}

export type Message = UserMessage | AssistantMessage | ToolMessage;

export interface ModelConfig {
  id: string;
  contextWindow: number;
  supportsTools: boolean;
  systemPromptStyle: 'system' | 'developer';
}
